import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'nav.categories': 'Categories',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.wishlist': 'Wishlist',
    'nav.login': 'Login',
    'nav.allCategories': 'All Categories',
    
    // Hero
    'hero.title': 'Discover Uzbekistan\'s',
    'hero.subtitle': 'ecological tourism',
    'hero.mobileTitle': 'Ecological Tourism',
    'hero.description': 'Unforgettable adventures in harmony with nature and professional guides',
    'hero.searchPlaceholder': 'Where do you want to go?',
    'hero.datePlaceholder': 'Select date',
    'hero.multiDay': 'Multi-day',
    'hero.singleDay': 'Single day',
    'hero.unusual': 'Unusual',
    'hero.findTours': 'Find tours',
    
    // Features
    'feature.mobileApp': 'Mobile App',
    'feature.download': 'Download',
    'feature.discounts': 'Discounts',
    'feature.upTo50': 'Up to 50%',
    'feature.newYear': 'New Year',
    'feature.tours2026': '2026 Tours',
    'feature.monthlyTours': 'Monthly Tours',
    'feature.special': 'Special',
    'feature.november': 'November',
    'feature.autumn': 'Autumn Season',
    
    // Filters
    'filters.found': 'tours found',
    'filters.sort': 'Sort',
    'filters.popularity': 'By popularity',
    'filters.price': 'By price',
    'filters.rating': 'By rating',
    'filters.duration': 'By duration',
    'filters.category': 'Category',
    'filters.allCategories': 'All categories',
    'filters.allSubcategories': 'All subcategories',
    'filters.durationFilter': 'Duration',
    'filters.priceFilter': 'Price',
    'filters.ratingFilter': 'Rating',
    'filters.allRatings': 'All ratings',
    'filters.stars': 'stars',
    'filters.specialOffers': 'Special offers',
    'filters.discountOnly': 'Discount only',
    'filters.guaranteedOnly': 'Guaranteed tours',
    'filters.language': 'Language',
    'filters.uzbek': 'Uzbek',
    'filters.russian': 'Russian',
    'filters.english': 'English',
    'filters.turkish': 'Turkish',
    'filters.clearFilters': 'Clear filters',
    'filters.days': 'days',
    'filters.som': 'som',
    'filters.maxPrice': 'Maximum price',
    
    // Tour cards
    'tour.author': 'Author',
    'tour.sponsored': 'Sponsored',
    'tour.recommended': 'Recommended',
    'tour.excursion': 'Excursion',
    'tour.reviews': 'reviews',
    'tour.days': 'days',
    'tour.people': 'people',
    'tour.from': 'from',
    'tour.som': 'som',
    
    // Pages
    'page.backButton': 'Back',
    'page.aboutUs': 'About Us',
    'page.contact': 'Contact',
    'page.wishlist': 'Wishlist',
    'page.login': 'Login',
    'page.register': 'Register',
    
    // About page
    'about.title': 'About Us',
    'about.companyName': 'DJIDALI ECOLOGICAL TOURISM',
    'about.description': 'A unique retreat into pristine nature, offering diverse eco-tourism experiences in beautiful natural landscapes.',
    'about.professionalService': 'Eco-Tourism',
    'about.professionalDesc': 'Forest trails and wildlife observation in pristine natural environments',
    'about.experiencedTeam': 'Agro-Tourism',
    'about.experiencedDesc': 'Farm experiences with seasonal work participation',
    'about.wideGeography': 'Team Building',
    'about.wideDesc': 'Professional guided experiences for groups',
    'about.safetyGuarantee': 'Safe Adventures',
    'about.safetyDesc': 'Safe and engaging routes with professional guides',
    'about.ourStory': 'Our Philosophy',
    'about.storyText1': 'We lovingly preserve the riches of this corner of nature and joyfully share them with guests. Our territory spans extensive forests, rivers, and lakes, offering breathtaking landscapes at every turn.',
    'about.storyText2': 'We provide diverse activities including eco-tourism with forest trails and wildlife observation, agro-tourism with farm experiences, team building activities, and sustainable nature engagement. Each experience is designed to help you disconnect from urban life and reconnect with nature.',
    'about.storyText3': 'More than just a destination, we offer a special atmosphere where visitors can immerse themselves in natural environments, interact with local agricultural practices, and find personal rejuvenation through warm hospitality and professional guidance.',
    'about.ourMission': 'Our Mission',
    'about.missionText': 'To preserve the natural riches of this unique corner of Uzbekistan and share unforgettable experiences with our guests through responsible and sustainable tourism practices.',
    'about.ourVision': 'Our Vision',
    'about.visionText': 'To be the leading eco-tourism destination where guests can experience authentic nature, disconnect from urban stress, and create lasting memories in pristine natural environments.',
    'about.contactUs': 'Contact Us',
    'about.contactDesc': 'Contact us for detailed information about our eco-tourism experiences',
    
    // Contact page
    'contact.title': 'Contact Us',
    'contact.contactInfo': 'Contact Information',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.workingHours': 'Working Hours',
    'contact.mondayFriday': 'Monday - Friday: 9:00 - 18:00',
    'contact.saturday': 'Saturday: 9:00 - 15:00',
    'contact.sunday': 'Sunday: Day off',
    'contact.socialMedia': 'Social Media',
    'contact.sendMessage': 'Send Message',
    'contact.name': 'Name',
    'contact.nameRequired': 'Name *',
    'contact.phoneRequired': 'Phone *',
    'contact.subject': 'Subject',
    'contact.subjectRequired': 'Subject *',
    'contact.selectSubject': 'Select subject',
    'contact.booking': 'Tour booking',
    'contact.info': 'Information request',
    'contact.complaint': 'Complaint',
    'contact.suggestion': 'Suggestion',
    'contact.other': 'Other',
    'contact.message': 'Message',
    'contact.messageRequired': 'Message *',
    'contact.messagePlaceholder': 'Write your message...',
    'contact.sending': 'Sending...',
    'contact.sendButton': 'Send Message',
    'contact.messageSent': 'Message sent!',
    'contact.messageDesc': 'We will contact you soon.',
    'contact.or': 'Or',
    'contact.ourLocation': 'Our Location',
    'contact.mapPlaceholder': 'Map will be displayed here',
    'contact.addressFull': 'Tashkent city, Yunusabad district',
    
    // Wishlist page
    'wishlist.title': 'Wishlist',
    'wishlist.saved': 'tours saved',
    'wishlist.clearAll': 'Clear all',
    'wishlist.share': 'Share',
    'wishlist.filters': 'Filters',
    'wishlist.sortBy': 'Sort by:',
    'wishlist.addedTime': 'Added time',
    'wishlist.byPrice': 'By price',
    'wishlist.byRating': 'By rating',
    'wishlist.byDuration': 'By duration',
    'wishlist.showing': 'Showing',
    'wishlist.of': 'of',
    'wishlist.empty': 'Wishlist is empty',
    'wishlist.emptyDesc': 'Add tours you like to your wishlist and view them later',
    'wishlist.viewTours': 'View Tours',
    'wishlist.tip': '💡 Tip: Click the heart icon on tour cards',
    'wishlist.youMightLike': 'You might like',
    'wishlist.recommendedDesc': 'Tours recommended based on your wishlist',
    
    // Login page
    'login.title': 'Login',
    'login.registerTitle': 'Register',
    'login.loginDesc': 'Login to your account to access safari tours',
    'login.registerDesc': 'Create a new account and discover safari tours',
    'login.fullName': 'Full Name',
    'login.phone': 'Phone Number',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.confirmPassword': 'Confirm Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.loginButton': 'Login',
    'login.registerButton': 'Register',
    'login.noAccount': 'Don\'t have an account? Register',
    'login.haveAccount': 'Have an account? Login',
    'login.telegram': 'Telegram',
    'login.sms': 'SMS',
    
    // Footer
    'footer.companyName': 'DJIDALI ECO TOURISM',
    'footer.companyDesc': 'Ecological tourism company',
    'footer.description': 'Discover the most beautiful natural places of Uzbekistan. We offer you an unforgettable experience with professional guides and safe safari tours.',
    'footer.quickLinks': 'Quick Links',
    'footer.home': 'Home',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.ecoTours': 'Ecological Tours',
    'footer.uzbekistanTours': 'Uzbekistan Tours',
    'footer.contactInfo': 'Contact Information',
    'footer.addressFull': 'Tashkent city, Yunusabad district,\nAmir Temur street, 108',
    'footer.workingHours': 'Mon-Fri: 9:00-18:00\nSat: 9:00-15:00',
    'footer.copyright': '© 2025 DJIDALI ECOLOGICAL TOURISM. All rights reserved.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.help': 'Help',
    
    // Common
    'common.loading': 'Loading...',
    'common.noResults': 'No tours found',
    'common.tryDifferentFilters': 'Try changing search filters',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.book': 'Book',
    'common.share': 'Share',
    'common.like': 'Like',
    'common.remove': 'Remove',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.logout': 'Logout'
  },
  ru: {
    // Header
    'nav.categories': 'Категории',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.wishlist': 'Избранное',
    'nav.login': 'Войти',
    'nav.adminPanel': 'Админ панель',
    'nav.userPanel': 'Мой кабинет',
    'nav.allCategories': 'Все категории',
    
    // Hero
    'hero.title': 'Откройте для себя',
    'hero.subtitle': 'экологический туризм Узбекистана',
    'hero.mobileTitle': 'Экологический туризм',
    'hero.description': 'Незабываемые приключения в гармонии с природой и профессиональными гидами',
    'hero.searchPlaceholder': 'Куда хотите поехать?',
    'hero.datePlaceholder': 'Выберите дату',
    'hero.multiDay': 'Многодневные',
    'hero.singleDay': 'Однодневные',
    'hero.unusual': 'Необычные',
    'hero.findTours': 'Найти туры',
    
    // Features
    'feature.mobileApp': 'Мобильное приложение',
    'feature.download': 'Скачать',
    'feature.discounts': 'Скидки',
    'feature.upTo50': 'До 50%',
    'feature.newYear': 'Новый год',
    'feature.tours2026': 'Туры 2026',
    'feature.monthlyTours': 'Туры месяца',
    'feature.special': 'Специальные',
    'feature.november': 'Ноябрь',
    'feature.autumn': 'Осенний сезон',
    
    // Filters
    'filters.found': 'туров найдено',
    'filters.sort': 'Сортировать',
    'filters.popularity': 'По популярности',
    'filters.price': 'По цене',
    'filters.rating': 'По рейтингу',
    'filters.duration': 'По длительности',
    'filters.category': 'Категория',
    'filters.allCategories': 'Все категории',
    'filters.allSubcategories': 'Все подкategории',
    'filters.durationFilter': 'Длительность',
    'filters.priceFilter': 'Цена',
    'filters.ratingFilter': 'Рейтинг',
    'filters.allRatings': 'Все рейтинги',
    'filters.stars': 'звезд',
    'filters.specialOffers': 'Специальные предложения',
    'filters.discountOnly': 'Только со скидками',
    'filters.guaranteedOnly': 'Гарантированные туры',
    'filters.language': 'Язык туров',
    'filters.uzbek': 'Узбекский',
    'filters.russian': 'Русский',
    'filters.english': 'Английский',
    'filters.turkish': 'Турецкий',
    'filters.clearFilters': 'Очистить фильтры',
    'filters.days': 'дней',
    'filters.som': 'сум',
    'filters.maxPrice': 'Максимальная цена',
    
    // Tour cards
    'tour.author': 'Авторский',
    'tour.sponsored': 'Спонсируемый',
    'tour.recommended': 'Рекомендуем',
    'tour.excursion': 'Экскурсионный',
    'tour.reviews': 'отзывов',
    'tour.days': 'дней',
    'tour.people': 'человек',
    'tour.from': 'от',
    'tour.som': 'сум',
    
    // Pages
    'page.backButton': 'Назад',
    'page.aboutUs': 'О нас',
    'page.contact': 'Контакты',
    'page.wishlist': 'Избранное',
    'page.login': 'Вход',
    'page.register': 'Регистрация',
    
    // About page
    'about.title': 'О нас',
    'about.companyName': 'DJIDALI ECOLOGICAL TOURISM',
    'about.description': 'Уникальное место отдыха на лоне природы, предлагающее разнообразные экотуристические программы в живописных природных ландшафтах.',
    'about.professionalService': 'Экотуризм',
    'about.professionalDesc': 'Лесные тропы и наблюдение за дикой природой в нетронутых природных средах',
    'about.experiencedTeam': 'Агротуризм',
    'about.experiencedDesc': 'Фермерский опыт с участием в сезонных работах',
    'about.wideGeography': 'Тимбилдинг',
    'about.wideDesc': 'Профессионально организованные программы для групп',
    'about.safetyGuarantee': 'Безопасные приключения',
    'about.safetyDesc': 'Безопасные и увлекательные маршруты с профессиональными гидами',
    'about.ourStory': 'Наша философия',
    'about.storyText1': 'Мы с любовью сохраняем богатства этого уголка природы и с радостью делимся ими с гостями. Наша территория охватывает обширные леса, реки и озера, предлагая захватывающие пейзажи на каждом шагу.',
    'about.storyText2': 'Мы предлагаем разнообразные виды деятельности, включая экотуризм с лесными тропами и наблюдением за дикой природой, агротуризм с фермерскими программами, тимбилдинг и устойчивое взаимодействие с природой. Каждый опыт разработан, чтобы помочь вам отключиться от городской жизни и восстановить связь с природой.',
    'about.storyText3': 'Больше, чем просто место назначения, мы предлагаем особую атмосферу, где посетители могут погрузиться в природную среду, взаимодействовать с местными сельскохозяйственными практиками и обрести личное обновление через теплое гостеприимство и профессиональное руководство.',
    'about.ourMission': 'Наша миссия',
    'about.missionText': 'Сохранить природные богатства этого уникального уголка Узбекистана и делиться незабываемыми впечатлениями с нашими гостями через ответственные и устойчивые туристические практики.',
    'about.ourVision': 'Наше видение',
    'about.visionText': 'Стать ведущим направлением экотуризма, где гости могут испытать аутентичную природу, отключиться от городского стресса и создать неизгладимые воспоминания в нетронутых природных средах.',
    'about.contactUs': 'Свяжитесь с нами',
    'about.contactDesc': 'Свяжитесь с нами для получения подробной информации о наших экотуристических программах',
    
    // Contact page
    'contact.title': 'Свяжитесь с нами',
    'contact.contactInfo': 'Контактная информация',
    'contact.phone': 'Телефон',
    'contact.email': 'Email',
    'contact.address': 'Адрес',
    'contact.workingHours': 'Рабочие часы',
    'contact.mondayFriday': 'Понедельник - Пятница: 9:00 - 18:00',
    'contact.saturday': 'Суббота: 9:00 - 15:00',
    'contact.sunday': 'Воскресенье: Выходной',
    'contact.socialMedia': 'Социальные сети',
    'contact.sendMessage': 'Отправить сообщение',
    'contact.name': 'Имя',
    'contact.nameRequired': 'Имя *',
    'contact.phoneRequired': 'Телефон *',
    'contact.subject': 'Тема',
    'contact.subjectRequired': 'Тема *',
    'contact.selectSubject': 'Выберите тему',
    'contact.booking': 'Бронирование тура',
    'contact.info': 'Запрос информации',
    'contact.complaint': 'Жалоба',
    'contact.suggestion': 'Предложение',
    'contact.other': 'Другое',
    'contact.message': 'Сообщение',
    'contact.messageRequired': 'Сообщение *',
    'contact.messagePlaceholder': 'Напишите ваше сообщение...',
    'contact.sending': 'Отправка...',
    'contact.sendButton': 'Отправить сообщение',
    'contact.messageSent': 'Сообщение отправлено!',
    'contact.messageDesc': 'Мы скоро свяжемся с вами.',
    'contact.or': 'Или',
    'contact.ourLocation': 'Наше местоположение',
    'contact.mapPlaceholder': 'Здесь будет отображена карта',
    'contact.addressFull': 'г. Ташкент, Юнусабадский район',
    
    // Wishlist page
    'wishlist.title': 'Избранное',
    'wishlist.saved': 'туров сохранено',
    'wishlist.clearAll': 'Очистить все',
    'wishlist.share': 'Поделиться',
    'wishlist.filters': 'Фильтры',
    'wishlist.sortBy': 'Сортировать по:',
    'wishlist.addedTime': 'Время добавления',
    'wishlist.byPrice': 'По цене',
    'wishlist.byRating': 'По рейтингу',
    'wishlist.byDuration': 'По длительности',
    'wishlist.showing': 'Показано',
    'wishlist.of': 'из',
    'wishlist.empty': 'Список избранного пуст',
    'wishlist.emptyDesc': 'Добавьте понравившиеся туры в избранное и просматривайте их позже',
    'wishlist.viewTours': 'Посмотреть туры',
    'wishlist.tip': '💡 Совет: Нажмите на значок сердца на карточках туров',
    'wishlist.youMightLike': 'Вам может понравиться',
    'wishlist.recommendedDesc': 'Туры, рекомендованные на основе вашего избранного',
    
    // Login page
    'login.title': 'Вход',
    'login.registerTitle': 'Регистрация',
    'login.loginDesc': 'Войдите в свой аккаунт для доступа к сафари турам',
    'login.registerDesc': 'Создайте новый аккаунт и откройте для себя сафари туры',
    'login.fullName': 'Полное имя',
    'login.phone': 'Номер телефона',
    'login.email': 'Email',
    'login.password': 'Пароль',
    'login.confirmPassword': 'Подтвердите пароль',
    'login.rememberMe': 'Запомнить меня',
    'login.forgotPassword': 'Забыли пароль?',
    'login.loginButton': 'Войти',
    'login.registerButton': 'Зарегистрироваться',
    'login.noAccount': 'Нет аккаунта? Зарегистрируйтесь',
    'login.haveAccount': 'Есть аккаунт? Войти',
    'login.telegram': 'Telegram',
    'login.sms': 'SMS',
    
    // Footer
    'footer.companyName': 'DJIDALI ECO TOURISM',
    'footer.companyDesc': 'Компания экологического туризма',
    'footer.description': 'Откройте для себя самые красивые природные места Узбекистана. Мы предлагаем вам незабываемые впечатления с профессиональными гидами и безопасными сафари турами.',
    'footer.quickLinks': 'Быстрые ссылки',
    'footer.home': 'Главная',
    'footer.aboutUs': 'О нас',
    'footer.contact': 'Контакты',
    'footer.ecoTours': 'Экологические туры',
    'footer.uzbekistanTours': 'Туры по Узбекистану',
    'footer.contactInfo': 'Контактная информация',
    'footer.addressFull': 'г. Ташкент, Юнусабадский район,\nул. Амира Темура, 108',
    'footer.workingHours': 'Пн-Пт: 9:00-18:00\nСб: 9:00-15:00',
    'footer.copyright': '© 2025 DJIDALI ECOLOGICAL TOURISM. Все права защищены.',
    'footer.privacyPolicy': 'Политика конфиденциальности',
    'footer.termsOfService': 'Условия использования',
    'footer.help': 'Помощь',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.noResults': 'Туры не найдены',
    'common.tryDifferentFilters': 'Попробуйте изменить фильтры поиска',
    'common.close': 'Закрыть',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.continue': 'Продолжить',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.previous': 'Предыдущий',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортировка',
    'common.view': 'Просмотр',
    'common.book': 'Забронировать',
    'common.share': 'Поделиться',
    'common.like': 'Нравится',
    'common.remove': 'Удалить',
    'common.add': 'Добавить',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.ok': 'ОК',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.warning': 'Предупреждение',
    'common.info': 'Информация',
    'common.logout': 'Выйти'
  },
  uz: {
    // Header
    'nav.categories': 'Kategoriyalar',
    'nav.about': 'Biz haqimizda',
    'nav.contact': 'Aloqa',
    'nav.wishlist': 'Sevimlilar',
    'nav.login': 'Kirish',
    'nav.adminPanel': 'Admin panel',
    'nav.userPanel': 'Kabinet',
    'nav.allCategories': 'Barcha kategoriyalar',
    
    // Hero
    'hero.title': 'O\'zbekistonning ekologik turizmini',
    'hero.subtitle': 'kashf eting',
    'hero.mobileTitle': 'Ekologik turizm',
    'hero.description': 'Tabiat bilan uyg\'unlikda unutilmas sarguzashtlar va professional gidlar bilan',
    'hero.searchPlaceholder': 'Qayerga bormoqchisiz?',
    'hero.datePlaceholder': 'Sanani tanlang',
    'hero.multiDay': 'Ko\'p kunlik',
    'hero.singleDay': 'Bir kunlik',
    'hero.unusual': 'G\'ayrioddiy',
    'hero.findTours': 'Turlarni topish',
    
    // Features
    'feature.mobileApp': 'Mobil ilova',
    'feature.download': 'Yuklab oling',
    'feature.discounts': 'Chegirmalar',
    'feature.upTo50': '50% gacha',
    'feature.newYear': 'Yangi yil',
    'feature.tours2026': '2026 turlari',
    'feature.monthlyTours': 'Oylik turlar',
    'feature.special': 'Maxsus',
    'feature.november': 'Noyabr',
    'feature.autumn': 'Kuz fasli',
    
    // Filters
    'filters.found': 'ta tur topildi',
    'filters.sort': 'Saralash',
    'filters.popularity': 'Mashhurligi bo\'yicha',
    'filters.price': 'Narx bo\'yicha',
    'filters.rating': 'Reyting bo\'yicha',
    'filters.duration': 'Davomiylik bo\'yicha',
    'filters.category': 'Kategoriya',
    'filters.allCategories': 'Barcha kategoriyalar',
    'filters.allSubcategories': 'Barcha subkategoriyalar',
    'filters.durationFilter': 'Davomiylik',
    'filters.priceFilter': 'Narx',
    'filters.ratingFilter': 'Reyting',
    'filters.allRatings': 'Barcha reytinglar',
    'filters.stars': 'yulduz',
    'filters.specialOffers': 'Maxsus takliflar',
    'filters.discountOnly': 'Faqat chegirmalilar',
    'filters.guaranteedOnly': 'Kafolatlangan turlar',
    'filters.language': 'Til',
    'filters.uzbek': 'O\'zbek tili',
    'filters.russian': 'Rus tili',
    'filters.english': 'Ingliz tili',
    'filters.turkish': 'Turk tili',
    'filters.clearFilters': 'Filtrlarni tozalash',
    'filters.days': 'kun',
    'filters.som': 'so\'m',
    'filters.maxPrice': 'Maksimal narx',
    
    // Tour cards
    'tour.author': 'Muallif',
    'tour.sponsored': 'Homiylik',
    'tour.recommended': 'Tavsiya',
    'tour.excursion': 'Ekskursiya',
    'tour.reviews': 'sharh',
    'tour.days': 'kun',
    'tour.people': 'kishi',
    'tour.from': 'dan',
    'tour.som': 'so\'m',
    
    // Pages
    'page.backButton': 'Orqaga',
    'page.aboutUs': 'Biz haqimizda',
    'page.contact': 'Aloqa',
    'page.wishlist': 'Sevimlilar',
    'page.login': 'Kirish',
    'page.register': 'Ro\'yxatdan o\'tish',
    
    // About page
    'about.title': 'Biz haqimizda',
    'about.companyName': 'DJIDALI ECOLOGICAL TOURISM',
    'about.description': 'Toza tabiatga noyob sayohat, go\'zal tabiy manzaralarda turli xil ekoturizm tajribalarini taklif etadi.',
    'about.professionalService': 'Ekoturizm',
    'about.professionalDesc': 'O\'rmon yo\'llari va yovvoyi tabiatni kuzatish toza tabiiy muhitda',
    'about.experiencedTeam': 'Agroturizm',
    'about.experiencedDesc': 'Fermer xo\'jaligi tajribasi va mavsumiy ishlarda ishtirok',
    'about.wideGeography': 'Jamoa qurish',
    'about.wideDesc': 'Guruhlar uchun professional tashkil etilgan dasturlar',
    'about.safetyGuarantee': 'Xavfsiz sarguzashtlar',
    'about.safetyDesc': 'Professional yo\'lboshchilar bilan xavfsiz va qiziqarli marshrutlar',
    'about.ourStory': 'Bizning falsafamiz',
    'about.storyText1': 'Biz tabiatning bu burchagidagi boyliklarni mehr bilan saqlaymiz va mehmonlar bilan baham ko\'ramiz. Bizning hududimiz keng o\'rmonlar, daryolar va ko\'llarni qamrab oladi, har qadamda hayratlanarli manzaralarni taqdim etadi.',
    'about.storyText2': 'Biz turli xil faoliyatlarni taklif etamiz: o\'rmon yo\'llari va yovvoyi tabiatni kuzatish bilan ekoturizm, fermer dasturlari bilan agroturizm, jamoa qurish va barqaror tabiat bilan muloqot. Har bir tajriba sizga shahar hayotidan uzilish va tabiat bilan aloqani tiklashda yordam berish uchun ishlab chiqilgan.',
    'about.storyText3': 'Faqat manzil emas, balki mehmonlar tabiiy muhitga sho\'ng\'ishi, mahalliy qishloq xo\'jaligi amaliyotlari bilan muloqot qilishlari va samimiy mehmondo\'stlik va professional yo\'lboshchilik orqali shaxsiy yangilanish topishi mumkin bo\'lgan maxsus atmosferani taklif etamiz.',
    'about.ourMission': 'Bizning missiyamiz',
    'about.missionText': 'O\'zbekistonning bu noyob burchagidagi tabiat boyliklarini saqlash va mas\'ul va barqaror turizm amaliyotlari orqali mehmonlarimiz bilan unutilmas tajribalarni ulashish.',
    'about.ourVision': 'Bizning vazifamiz',
    'about.visionText': 'Mehmonlar haqiqiy tabiatni boshdan kechira oladigan, shahar stressidan uzila oladigan va toza tabiiy muhitda unutilmas xotiralar yarata oladigan etakchi ekoturizm yo\'nalishiga aylanish.',
    'about.contactUs': 'Biz bilan bog\'laning',
    'about.contactDesc': 'Ekoturizm dasturlarimiz haqida batafsil ma\'lumot olish uchun biz bilan bog\'laning',
    
    // Contact page
    'contact.title': 'Biz bilan bog\'laning',
    'contact.contactInfo': 'Aloqa ma\'lumotlari',
    'contact.phone': 'Telefon',
    'contact.email': 'Email',
    'contact.address': 'Manzil',
    'contact.workingHours': 'Ish vaqti',
    'contact.mondayFriday': 'Dushanba - Juma: 9:00 - 18:00',
    'contact.saturday': 'Shanba: 9:00 - 15:00',
    'contact.sunday': 'Yakshanba: Dam olish kuni',
    'contact.socialMedia': 'Ijtimoiy tarmoqlar',
    'contact.sendMessage': 'Xabar yuborish',
    'contact.name': 'Ism',
    'contact.nameRequired': 'Ism *',
    'contact.phoneRequired': 'Telefon *',
    'contact.subject': 'Mavzu',
    'contact.subjectRequired': 'Mavzu *',
    'contact.selectSubject': 'Mavzuni tanlang',
    'contact.booking': 'Tur bronlash',
    'contact.info': 'Ma\'lumot so\'rash',
    'contact.complaint': 'Shikoyat',
    'contact.suggestion': 'Taklif',
    'contact.other': 'Boshqa',
    'contact.message': 'Xabar',
    'contact.messageRequired': 'Xabar *',
    'contact.messagePlaceholder': 'Xabaringizni yozing...',
    'contact.sending': 'Yuborilmoqda...',
    'contact.sendButton': 'Xabar yuborish',
    'contact.messageSent': 'Xabar yuborildi!',
    'contact.messageDesc': 'Tez orada siz bilan bog\'lanamiz.',
    'contact.or': 'Yoki',
    'contact.ourLocation': 'Bizning joylashuvimiz',
    'contact.mapPlaceholder': 'Xarita bu yerda ko\'rsatiladi',
    'contact.addressFull': 'Toshkent shahri, Yunusobod tumani',
    
    // Wishlist page
    'wishlist.title': 'Sevimlilar',
    'wishlist.saved': 'ta tur saqlangan',
    'wishlist.clearAll': 'Barchasini o\'chirish',
    'wishlist.share': 'Ulashish',
    'wishlist.filters': 'Filtrlar',
    'wishlist.sortBy': 'Saralash:',
    'wishlist.addedTime': 'Qo\'shilgan vaqt bo\'yicha',
    'wishlist.byPrice': 'Narx bo\'yicha',
    'wishlist.byRating': 'Reyting bo\'yicha',
    'wishlist.byDuration': 'Davomiylik bo\'yicha',
    'wishlist.showing': 'Ko\'rsatilmoqda',
    'wishlist.of': 'dan',
    'wishlist.empty': 'Sevimlilar ro\'yxati bo\'sh',
    'wishlist.emptyDesc': 'Yoqgan turlaringizni sevimlilar ro\'yxatiga qo\'shing va keyinroq ko\'ring',
    'wishlist.viewTours': 'Turlarni ko\'rish',
    'wishlist.tip': '💡 Maslahat: Tur kartasidagi yurak belgisini bosing',
    'wishlist.youMightLike': 'Sizga yoqishi mumkin',
    'wishlist.recommendedDesc': 'Sevimlilaringiz asosida tavsiya etilgan turlar',
    
    // Login page
    'login.title': 'Hisobga kirish',
    'login.registerTitle': 'Ro\'yxatdan o\'tish',
    'login.loginDesc': 'Safari turlariga kirish uchun hisobingizga kiring',
    'login.registerDesc': 'Yangi hisob yaratib safari turlarini kashf eting',
    'login.fullName': 'To\'liq ism',
    'login.phone': 'Telefon raqam',
    'login.email': 'Email',
    'login.password': 'Parol',
    'login.confirmPassword': 'Parolni tasdiqlang',
    'login.rememberMe': 'Meni eslab qol',
    'login.forgotPassword': 'Parolni unutdingizmi?',
    'login.loginButton': 'Kirish',
    'login.registerButton': 'Ro\'yxatdan o\'tish',
    'login.noAccount': 'Hisobingiz yo\'qmi? Ro\'yxatdan o\'ting',
    'login.haveAccount': 'Hisobingiz bormi? Kirish',
    'login.telegram': 'Telegram',
    'login.sms': 'SMS',
    
    // Footer
    'footer.companyName': 'DJIDALI ECO TOURISM',
    'footer.companyDesc': 'Ekologik turizm kompaniyasi',
    'footer.description': 'O\'zbekistonning eng go\'zal tabiat joylarini kashf eting. Biz professional gidlar va xavfsiz safari turlari bilan sizga unutilmas tajriba taqdim etamiz.',
    'footer.quickLinks': 'Tezkor havolalar',
    'footer.home': 'Bosh sahifa',
    'footer.aboutUs': 'Biz haqimizda',
    'footer.contact': 'Aloqa',
    'footer.ecoTours': 'Ekologik turlar',
    'footer.uzbekistanTours': 'O\'zbekiston turlari',
    'footer.contactInfo': 'Aloqa ma\'lumotlari',
    'footer.addressFull': 'Toshkent shahri, Yunusobod tumani,\nAmir Temur ko\'chasi, 108-uy',
    'footer.workingHours': 'Dush-Juma: 9:00-18:00\nShanba: 9:00-15:00',
    'footer.copyright': '© 2025 DJIDALI ECOLOGICAL TOURISM. Barcha huquqlar himoyalangan.',
    'footer.privacyPolicy': 'Maxfiylik siyosati',
    'footer.termsOfService': 'Foydalanish shartlari',
    'footer.help': 'Yordam',
    
    // Common
    'common.loading': 'Yuklanmoqda...',
    'common.noResults': 'Turlar topilmadi',
    'common.tryDifferentFilters': 'Qidiruv filtrlarini o\'zgartirib ko\'ring',
    'common.close': 'Yopish',
    'common.save': 'Saqlash',
    'common.cancel': 'Bekor qilish',
    'common.continue': 'Davom etish',
    'common.back': 'Orqaga',
    'common.next': 'Keyingi',
    'common.previous': 'Oldingi',
    'common.search': 'Qidirish',
    'common.filter': 'Filtr',
    'common.sort': 'Saralash',
    'common.view': 'Ko\'rish',
    'common.book': 'Bron qilish',
    'common.share': 'Ulashish',
    'common.like': 'Yoqtirish',
    'common.remove': 'O\'chirish',
    'common.add': 'Qo\'shish',
    'common.edit': 'Tahrirlash',
    'common.delete': 'O\'chirish',
    'common.confirm': 'Tasdiqlash',
    'common.yes': 'Ha',
    'common.no': 'Yo\'q',
    'common.ok': 'OK',
    'common.error': 'Xato',
    'common.success': 'Muvaffaqiyat',
    'common.warning': 'Ogohlantirish',
    'common.info': 'Ma\'lumot',
    'common.logout': 'Chiqish'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }

    // fallback to Russian, then English before returning key
    if (translations.ru && translations.ru[key]) {
      return translations.ru[key];
    }

    if (translations.en && translations.en[key]) {
      return translations.en[key];
    }

    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};