import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru' | 'uz';

interface TranslateArgs {
  ru: string;
  uz: string;
  en?: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translate: (input: TranslateArgs | string) => string;
}

const translations = {
  en: {
    // Header
    'nav.categories': 'Categories',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.whyUs': 'Why Us',
    'nav.wishlist': 'Wishlist',
    'nav.login': 'Login',
    'nav.allCategories': 'All Categories',
    
    // Hero
    'hero.title': 'Discover Uzbekistan\'s',
    'hero.subtitle': 'ecological tourism',
    'hero.mobileTitle': 'Ecological Tourism',
    'hero.description': 'Unforgettable adventures in harmony with nature and professional guides',
    'hero.searchPlaceholder': 'Where do you want to go?',
    'hero.datePlaceholder': 'Select date',
    'hero.rangeSep12To20': '12-20 September',
    'hero.rangeSep21To30': '21-30 September',
    'hero.rangeOct01To10': '1-10 October',
    'hero.multiDay': 'Multi-day',
    'hero.singleDay': 'Single day',
    'hero.unusual': 'Unusual',
    'hero.findTours': 'Find tours',
    'hero.countryLabel': 'Country',
    'hero.dateLabel': 'Date range',
    'hero.participantsLabel': 'Participants',
    'hero.tourTypeLabel': 'Tour type',
    'hero.participantsFamily': 'Family',
    'hero.participantsSolo': 'Solo traveler',
    'hero.participantsCouple': 'Couple',
    'hero.participantsGroup': 'Group',
    'hero.hunting': 'Hunting',
    'hero.agro': 'Agrotourism',
    'hero.teamBuilding': 'Team building',
    
    // Features
    'feature.mobileApp': 'Mobile App',
    'feature.download': 'Download',
    'feature.discounts': 'Discounts',
    'feature.upTo50': 'Up to 50%',
    'feature.newYear': 'New Year',
    'feature.tours2026': '2026 Tours',
    'feature.monthlyTours': 'Monthly Tours',
    'feature.special': 'Special',
    'feature.november': 'November',
    'feature.autumn': 'Autumn Season',
    
    // Filters
    'filters.found': 'tours found',
    'filters.sort': 'Sort',
    'filters.popularity': 'By popularity',
    'filters.price': 'By price',
    'filters.rating': 'By rating',
    'filters.filter': 'Filter',
    'filters.duration': 'By duration',
    'filters.category': 'Category',
    'filters.allCategories': 'All categories',
    'filters.allSubcategories': 'All subcategories',
    'filters.durationFilter': 'Duration',
    'filters.priceFilter': 'Price',
    'filters.ratingFilter': 'Rating',
    'filters.allRatings': 'All ratings',
    'filters.stars': 'stars',
    'filters.specialOffers': 'Special offers',
    'filters.discountOnly': 'Discount only',
    'filters.guaranteedOnly': 'Guaranteed tours',
    'filters.language': 'Language',
    'filters.uzbek': 'Uzbek',
    'filters.russian': 'Russian',
    'filters.english': 'English',
    'filters.turkish': 'Turkish',
    'filters.clearFilters': 'Clear filters',
    'filters.days': 'days',
    'filters.som': 'som',
    'filters.maxPrice': 'Maximum price',
    'tourList.availableDirections': '14 available destinations',
    
    // Tour cards
    'tour.author': 'Author',
    'tour.sponsored': 'Sponsored',
    'tour.recommended': 'Recommended',
    'tour.excursion': 'Excursion',
    'tour.reviews': 'reviews',
    'tour.days': 'days',
    'tour.people': 'people',
    'tour.upTo': 'up to',
    'tour.from': 'from',
    'tour.som': 'som',
    'tour.defaultLocation': 'Uzbekistan',
    'tour.priceFrom': 'Tour price from',
    'tour.durationLabel': 'Tour duration',
    'tour.minAge': 'Minimum age',
    'tour.defaultMinAge': 'from 12 years',
    'tour.type': 'Tour type',
    'tour.defaultType': 'Ecotourism',
    'tour.difficulty': 'Difficulty',
    'tour.defaultDifficulty': 'Easy',
    'tour.years': 'years',
    'tour.about': 'About the tour',
    'tour.included': 'Included',
    'tour.excluded': 'Not included',
    'tour.moments': 'Tour highlights',
    'tour.program': 'Tour program',
    'tour.day': 'Day',
    'tour.defaultDetailLocation': 'Uzbekistan, Chatkal Range',
    'tour.descriptionFallback': 'This tour immerses you in pristine nature with guided trails, comfortable eco-lodging, and inclusive meals.',
    'tour.defaultIncluded1': 'Accommodation in eco-lodges',
    'tour.defaultIncluded2': 'Full board meals',
    'tour.defaultIncluded3': 'Professional guide services',
    'tour.defaultIncluded4': 'Transfers and transport',
    'tour.defaultIncluded5': 'Excursions according to program',
    'tour.defaultExcluded1': 'Personal expenses',
    'tour.defaultExcluded2': 'Alcoholic beverages',
    'tour.defaultExcluded3': 'Medical insurance',
    'tour.defaultExcluded4': 'Souvenirs and extra equipment',
    'tour.defaultExcluded5': 'Optional excursions on request',
    'tour.bookingTitle': 'Booking & payment',
    'tour.bookingDescription': 'Send a booking request and complete the payment through Click once availability is confirmed.',
    'tour.bookNow': 'Book this tour',
    'tour.loginToBook': 'Login to book',
    
    // Pages
    'page.backButton': 'Back',
    'page.aboutUs': 'About Us',
    'page.contact': 'Contact',
    'page.wishlist': 'Wishlist',
    'page.login': 'Login',
    'page.register': 'Register',
    
    // About page
    'about.title': 'About Us',
    'about.companyName': 'DJIDALI ECOLOGICAL TOURISM',
    'about.description': 'A unique retreat into pristine nature, offering diverse eco-tourism experiences in beautiful natural landscapes.',
    'about.professionalService': 'Eco-Tourism',
    'about.professionalDesc': 'Forest trails and wildlife observation in pristine natural environments',
    'about.experiencedTeam': 'Agro-Tourism',
    'about.experiencedDesc': 'Farm experiences with seasonal work participation',
    'about.wideGeography': 'Team Building',
    'about.wideDesc': 'Professional guided experiences for groups',
    'about.safetyGuarantee': 'Safe Adventures',
    'about.safetyDesc': 'Safe and engaging routes with professional guides',
    'about.ourStory': 'Our Philosophy',
    'about.storyText1': 'We lovingly preserve the riches of this corner of nature and joyfully share them with guests. Our territory spans extensive forests, rivers, and lakes, offering breathtaking landscapes at every turn.',
    'about.storyText2': 'We provide diverse activities including eco-tourism with forest trails and wildlife observation, agro-tourism with farm experiences, team building activities, and sustainable nature engagement. Each experience is designed to help you disconnect from urban life and reconnect with nature.',
    'about.storyText3': 'More than just a destination, we offer a special atmosphere where visitors can immerse themselves in natural environments, interact with local agricultural practices, and find personal rejuvenation through warm hospitality and professional guidance.',
    'about.ourMission': 'Our Mission',
    'about.missionText': 'To preserve the natural riches of this unique corner of Uzbekistan and share unforgettable experiences with our guests through responsible and sustainable tourism practices.',
    'about.ourVision': 'Our Vision',
    'about.visionText': 'To be the leading eco-tourism destination where guests can experience authentic nature, disconnect from urban stress, and create lasting memories in pristine natural environments.',
    'about.contactUs': 'Contact Us',
    'about.contactDesc': 'Contact us for detailed information about our eco-tourism experiences',
    
    // Contact page
    'contact.title': 'Contact Us',
    'contact.contactInfo': 'Contact Information',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.workingHours': 'Working Hours',
    'contact.mondayFriday': 'Monday - Friday: 9:00 - 18:00',
    'contact.saturday': 'Saturday: 9:00 - 15:00',
    'contact.sunday': 'Sunday: Day off',
    'contact.socialMedia': 'Social Media',
    'contact.sendMessage': 'Send Message',
    'contact.name': 'Name',
    'contact.nameRequired': 'Name *',
    'contact.phoneRequired': 'Phone *',
    'contact.subject': 'Subject',
    'contact.subjectRequired': 'Subject *',
    'contact.selectSubject': 'Select subject',
    'contact.booking': 'Tour booking',
    'contact.info': 'Information request',
    'contact.complaint': 'Complaint',
    'contact.suggestion': 'Suggestion',
    'contact.other': 'Other',
    'contact.message': 'Message',
    'contact.messageRequired': 'Message *',
    'contact.messagePlaceholder': 'Write your message...',
    'contact.sending': 'Sending...',
    'contact.sendButton': 'Send Message',
    'contact.messageSent': 'Message sent!',
    'contact.messageDesc': 'We will contact you soon.',
    'contact.or': 'Or',
    'contact.ourLocation': 'Our Location',
    'contact.mapPlaceholder': 'Map will be displayed here',
    'contact.addressFull': 'Tashkent city, Yunusabad district',
    'contact.contactHeadline': 'Get in touch with us',
    'contact.phoneLabel': 'Phone number',
    'contact.connectTitle': 'Let’s talk',
    'contact.connectDescription': 'We are always open for collaboration and ready to help you plan an unforgettable trip.',
    'contact.workingHoursValue': '09:00 — 18:00',
    'contact.mapImageAlt': 'Journey through pristine Uzbek nature',
    'contact.heroHighlightLine1': 'Journey',
    'contact.heroHighlightLine2': 'through Dalverzin',
    
    // Home page
    'home.about.label': 'About us',
    'home.about.title': 'About us',
    'home.about.highlight': 'the journey of your dreams',
    'home.about.text1': 'We help you find ',
    'home.about.text2': 'and discover the beauty of nature in its finest manifestations.',
    'home.about.description': 'Here you will find routes, landscapes, and experiences that stay in memory forever. We guide you every step of the way so your trip feels effortless and inspiring.',
    'home.about.bottomText': 'Here you will find routes, landscapes, and experiences that will stay in your memory forever',
    'home.about.imageAlt': 'Nature',
    'home.popular.label': 'Popular tours',
    'home.popular.heading': 'Popular tours',
    'home.popular.subtitle': '14 destinations available',
    'home.popular.loading': 'Loading curated tours...',
    'home.popular.defaultBadge': 'Eco-tour',
    'home.popular.emptyState': 'Tours are temporarily unavailable. Please try again later.',
    'home.popular.viewAll': 'View all tours',
    'home.popular.daysAndPeople': '{duration} days, up to {people} people',
    'home.popular.planIncludes': 'Plan includes',
    'home.popular.from': 'From',
    'home.whyUs.label': 'Why us',
    'home.whyUs.heading': 'From idea to dream realization',
    'home.whyUs.subtitle': 'Every route is curated by the DJIDALI team',
    'home.whyUs.cardTitle': 'Why choose us',
    'home.whyUs.cardDescription': 'We combine the power of nature, the experience of our team, and tailored itineraries so that every trip becomes truly special.',
    'home.experience.team': 'Expert team',
    'home.experience.nature': 'Pristine nature experiences',
    'home.experience.comfort': 'Comfortable stays',
    'home.experience.routes': 'Unique routes',

    // Why Us page
    'whyUs.hero.tagline': 'DJIDALI • WHY US',
    'whyUs.hero.title': 'We take you where nature speaks first',
    'whyUs.hero.description': 'DJIDALI blends nature, comfort, and expertise to craft journeys you will never forget.',
    'whyUs.hero.primaryCta': 'Discover unique routes',
    'whyUs.hero.statTravelers': 'thousand happy travelers',
    'whyUs.hero.statPackages': 'curated tour packages',
    'whyUs.hero.statYears': 'years of experience',
    'whyUs.section1.title': 'Discover unique itineraries',
    'whyUs.section1.paragraph1': 'Our routes are designed for those who seek a deeper connection with nature. Each journey is carefully curated to balance comfort, thoughtful logistics, and access to untouched landscapes.',
    'whyUs.section1.paragraph2': 'Walk the paths known only to local rangers and see the world through the eyes of those who truly know it.',
    'whyUs.section2.paragraph': 'We ensure safety, guidance, and comfort at every step. Whether you prefer a calm retreat or an adventure-filled program, DJIDALI offers experiences tailored to your pace.',
    'whyUs.section3.paragraph': 'DJIDALI is more than routes—it is a meeting with living nature, breathing in the rhythm of Uzbekistan, and leaving with a heart full of freedom.',
    'whyUs.gallery.altForestPath': 'Forest trail',
    'whyUs.gallery.altMountain': 'Mountain landscape',
    'whyUs.gallery.altCanyon': 'Canyon trail',
    'whyUs.gallery.altRiverValley': 'River valley',
    'whyUs.gallery.altRockyRoute': 'Rocky route',
    'whyUs.gallery.altField': 'Open field',
    'whyUs.gallery.altThicket': 'Dense thicket',
    'whyUs.gallery.altLandscape': 'Uzbekistan landscape',
    'whyUs.gallery.altForestMassif': 'Forest massif',

    // Wishlist page
    'wishlist.title': 'Wishlist',
    'wishlist.saved': 'tours saved',
    'wishlist.clearAll': 'Clear all',
    'wishlist.share': 'Share',
    'wishlist.filters': 'Filters',
    'wishlist.sortBy': 'Sort by:',
    'wishlist.addedTime': 'Added time',
    'wishlist.byPrice': 'By price',
    'wishlist.byRating': 'By rating',
    'wishlist.byDuration': 'By duration',
    'wishlist.showing': 'Showing',
    'wishlist.of': 'of',
    'wishlist.empty': 'Wishlist is empty',
    'wishlist.emptyDesc': 'Add tours you like to your wishlist and view them later',
    'wishlist.viewTours': 'View Tours',
    'wishlist.tip': '💡 Tip: Click the heart icon on tour cards',
    'wishlist.youMightLike': 'You might like',
    'wishlist.recommendedDesc': 'Tours recommended based on your wishlist',
    
    // Login page
    'login.title': 'Login',
    'login.registerTitle': 'Register',
    'login.loginDesc': 'Login to your account to access safari tours',
    'login.registerDesc': 'Create a new account and discover safari tours',
    'login.backToHome': 'Back to homepage',
    'login.sideHeading': 'Travel made personal',
    'login.sideSubtitle': 'Plan immersive eco tours with local experts and tailor-made comfort.',
    'login.sideStat1': 'Curated experiences across Uzbekistan',
    'login.sideStat2': 'Expert guides & dedicated support',
    'login.sideStat3': 'Secure bookings with flexible payments',
    'login.fullName': 'Full Name',
    'login.phone': 'Phone Number',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.confirmPassword': 'Confirm Password',
    'login.firstNameLabel': 'First name',
    'login.lastNameLabel': 'Last name',
    'login.firstNamePlaceholder': 'Your first name',
    'login.lastNamePlaceholder': 'Your last name',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.loginButton': 'Login',
    'login.registerButton': 'Register',
    'login.noAccount': 'Don\'t have an account? Register',
    'login.haveAccount': 'Have an account? Login',
    'login.telegram': 'Telegram',
    'login.sms': 'SMS',
    'login.passwordMismatchError': 'Passwords do not match',
    'login.passwordMinLengthError': 'Password must be at least 8 characters',
    'login.genericError': 'Something went wrong. Please try again.',
    'login.loading': 'Loading...',
    'login.phoneLabel': 'Phone number',
    'login.phonePlaceholder': '+998 90 123 45 67',
    'login.phoneHint': 'Use a valid phone number so our team can contact you',
    'login.phoneRequiredError': 'Phone number is required',
    'login.phoneInvalidError': 'Enter a valid phone number',
    'login.accessLabel': 'Account access',
    'login.createLabel': 'Create account',
    'login.joinCommunityBanner': 'Join the DJIDALI community',
    
    // Footer
    'footer.companyName': 'DJIDALI ECO TOURISM',
    'footer.companyDesc': 'Ecological tourism company',
    'footer.description': 'Discover the most beautiful natural places of Uzbekistan. We offer you an unforgettable experience with professional guides and safe safari tours.',
    'footer.quickLinks': 'Quick Links',
    'footer.section.about': 'About',
    'footer.section.tourTypes': 'Tour types',
    'footer.section.whyUs': 'Why choose us',
    'footer.section.social': 'Social media',
    'footer.home': 'Home',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.ecoTours': 'Ecological Tours',
    'footer.uzbekistanTours': 'Uzbekistan Tours',
    'footer.link.gallery': 'Gallery',
    'footer.link.team': 'Our team',
    'footer.tourType.eco': 'Ecotourism',
    'footer.tourType.agro': 'Agrotourism',
    'footer.tourType.teamBuilding': 'Team building',
    'footer.tourType.sportShooting': 'Sport shooting',
    'footer.tourType.hunting': 'Hunting tourism',
    'footer.tourType.uzbekistan': 'Tours in Uzbekistan',
    'footer.contactInfo': 'Contact Information',
    'footer.addressFull': 'Tashkent city, Yunusabad district,\nAmir Temur street, 108',
    'footer.workingHours': 'Mon-Fri: 9:00-18:00\nSat: 9:00-15:00',
    'footer.copyright': '© 2025 DJIDALI ECOLOGICAL TOURISM. All rights reserved.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.help': 'Help',
    'footer.siteSections': 'Site sections',
    'footer.contactPrompt': 'Contact us',
    'footer.connectWithUs': 'Stay connected',
    
    // Common
    'common.loading': 'Loading...',
    'common.noResults': 'No tours found',
    'common.tryDifferentFilters': 'Try changing search filters',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.book': 'Book',
    'common.share': 'Share',
    'common.like': 'Like',
    'common.remove': 'Remove',
    'common.refresh': 'Refresh list',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.logout': 'Logout',
    'common.currencyUzbekSum': 'UZS'
  },
  ru: {
    // Header
    'nav.categories': 'Категории',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.whyUs': 'Почему мы',
    'nav.wishlist': 'Избранное',
    'nav.login': 'Войти',
    'nav.adminPanel': 'Админ панель',
    'nav.userPanel': 'Мой кабинет',
    'nav.allCategories': 'Все категории',
    
    // Hero
    'hero.title': 'Откройте для себя',
    'hero.subtitle': 'экологический туризм Узбекистана',
    'hero.mobileTitle': 'Экологический туризм',
    'hero.description': 'Незабываемые приключения в гармонии с природой и профессиональными гидами',
    'hero.searchPlaceholder': 'Куда хотите поехать?',
    'hero.datePlaceholder': 'Выберите дату',
    'hero.rangeSep12To20': '12–20 сентября',
    'hero.rangeSep21To30': '21–30 сентября',
    'hero.rangeOct01To10': '1–10 октября',
    'hero.multiDay': 'Многодневные',
    'hero.singleDay': 'Однодневные',
    'hero.unusual': 'Необычные',
    'hero.findTours': 'Найти туры',
    'hero.countryLabel': 'Страна',
    'hero.dateLabel': 'Диапазон дат',
    'hero.participantsLabel': 'Участники',
    'hero.tourTypeLabel': 'Тип тура',
    'hero.participantsFamily': 'Семья',
    'hero.participantsSolo': 'Один путешественник',
    'hero.participantsCouple': 'Пара',
    'hero.participantsGroup': 'Группа',
    'hero.hunting': 'Охота',
    'hero.agro': 'Агротуризм',
    'hero.teamBuilding': 'Тимбилдинг',
    
    // Features
    'feature.mobileApp': 'Мобильное приложение',
    'feature.download': 'Скачать',
    'feature.discounts': 'Скидки',
    'feature.upTo50': 'До 50%',
    'feature.newYear': 'Новый год',
    'feature.tours2026': 'Туры 2026',
    'feature.monthlyTours': 'Туры месяца',
    'feature.special': 'Специальные',
    'feature.november': 'Ноябрь',
    'feature.autumn': 'Осенний сезон',
    
    // Filters
    'filters.found': 'туров найдено',
    'filters.sort': 'Сортировать',
    'filters.popularity': 'По популярности',
    'filters.price': 'По цене',
    'filters.rating': 'По рейтингу',
    'filters.filter': 'Фильтр',
    'filters.duration': 'По длительности',
    'filters.category': 'Категория',
    'filters.allCategories': 'Все категории',
    'filters.allSubcategories': 'Все подкategории',
    'filters.durationFilter': 'Длительность',
    'filters.priceFilter': 'Цена',
    'filters.ratingFilter': 'Рейтинг',
    'filters.allRatings': 'Все рейтинги',
    'filters.stars': 'звезд',
    'filters.specialOffers': 'Специальные предложения',
    'filters.discountOnly': 'Только со скидками',
    'filters.guaranteedOnly': 'Гарантированные туры',
    'filters.language': 'Язык туров',
    'filters.uzbek': 'Узбекский',
    'filters.russian': 'Русский',
    'filters.english': 'Английский',
    'filters.turkish': 'Турецкий',
    'filters.clearFilters': 'Очистить фильтры',
    'filters.days': 'дней',
    'filters.som': 'сум',
    'filters.maxPrice': 'Максимальная цена',
    'tourList.availableDirections': '14 доступных направлений',
    
    // Tour cards
    'tour.author': 'Авторский',
    'tour.sponsored': 'Спонсируемый',
    'tour.recommended': 'Рекомендуем',
    'tour.excursion': 'Экскурсионный',
    'tour.reviews': 'отзывов',
    'tour.days': 'дней',
    'tour.people': 'человек',
    'tour.upTo': 'до',
    'tour.from': 'от',
    'tour.som': 'сум',
    'tour.defaultLocation': 'Узбекистан',
    'tour.priceFrom': 'Стоимость тура от',
    'tour.durationLabel': 'Продолжительность тура',
    'tour.minAge': 'Минимальный возраст',
    'tour.defaultMinAge': 'от 12 лет',
    'tour.type': 'Тип тура',
    'tour.defaultType': 'Экотуризм',
    'tour.difficulty': 'Сложность',
    'tour.defaultDifficulty': 'Легкое',
    'tour.years': 'лет',
    'tour.about': 'О туре',
    'tour.included': 'Что включено',
    'tour.excluded': 'Что не входит',
    'tour.moments': 'Моменты из тура',
    'tour.program': 'Программа тура',
    'tour.day': 'День',
    'tour.defaultDetailLocation': 'Узбекистан, Чаткальский хребет',
    'tour.descriptionFallback': 'Этот тур позволяет ощутить атмосферу первозданной природы с продуманными маршрутами, уютным проживанием и полноценным питанием.',
    'tour.defaultIncluded1': 'Проживание в эко-домиках',
    'tour.defaultIncluded2': 'Трёхразовое питание',
    'tour.defaultIncluded3': 'Услуги профессионального гида',
    'tour.defaultIncluded4': 'Трансфер и транспорт',
    'tour.defaultIncluded5': 'Экскурсии по программе',
    'tour.defaultExcluded1': 'Личные расходы',
    'tour.defaultExcluded2': 'Алкогольные напитки',
    'tour.defaultExcluded3': 'Медицинская страховка',
    'tour.defaultExcluded4': 'Сувениры и дополнительное снаряжение',
    'tour.defaultExcluded5': 'Дополнительные экскурсии по запросу',
    'tour.bookingTitle': 'Бронирование и оплата',
    'tour.bookingDescription': 'Отправьте заявку и завершите оплату через Click после подтверждения доступности нашим менеджером.',
    'tour.bookNow': 'Забронировать тур',
    'tour.loginToBook': 'Войдите, чтобы забронировать',
    
    // Pages
    'page.backButton': 'Назад',
    'page.aboutUs': 'О нас',
    'page.contact': 'Контакты',
    'page.wishlist': 'Избранное',
    'page.login': 'Вход',
    'page.register': 'Регистрация',
    
    // About page
    'about.title': 'О нас',
    'about.companyName': 'DJIDALI ECOLOGICAL TOURISM',
    'about.description': 'Уникальное место отдыха на лоне природы, предлагающее разнообразные экотуристические программы в живописных природных ландшафтах.',
    'about.professionalService': 'Экотуризм',
    'about.professionalDesc': 'Лесные тропы и наблюдение за дикой природой в нетронутых природных средах',
    'about.experiencedTeam': 'Агротуризм',
    'about.experiencedDesc': 'Фермерский опыт с участием в сезонных работах',
    'about.wideGeography': 'Тимбилдинг',
    'about.wideDesc': 'Профессионально организованные программы для групп',
    'about.safetyGuarantee': 'Безопасные приключения',
    'about.safetyDesc': 'Безопасные и увлекательные маршруты с профессиональными гидами',
    'about.ourStory': 'Наша философия',
    'about.storyText1': 'Мы с любовью сохраняем богатства этого уголка природы и с радостью делимся ими с гостями. Наша территория охватывает обширные леса, реки и озера, предлагая захватывающие пейзажи на каждом шагу.',
    'about.storyText2': 'Мы предлагаем разнообразные виды деятельности, включая экотуризм с лесными тропами и наблюдением за дикой природой, агротуризм с фермерскими программами, тимбилдинг и устойчивое взаимодействие с природой. Каждый опыт разработан, чтобы помочь вам отключиться от городской жизни и восстановить связь с природой.',
    'about.storyText3': 'Больше, чем просто место назначения, мы предлагаем особую атмосферу, где посетители могут погрузиться в природную среду, взаимодействовать с местными сельскохозяйственными практиками и обрести личное обновление через теплое гостеприимство и профессиональное руководство.',
    'about.ourMission': 'Наша миссия',
    'about.missionText': 'Сохранить природные богатства этого уникального уголка Узбекистана и делиться незабываемыми впечатлениями с нашими гостями через ответственные и устойчивые туристические практики.',
    'about.ourVision': 'Наше видение',
    'about.visionText': 'Стать ведущим направлением экотуризма, где гости могут испытать аутентичную природу, отключиться от городского стресса и создать неизгладимые воспоминания в нетронутых природных средах.',
    'about.contactUs': 'Свяжитесь с нами',
    'about.contactDesc': 'Свяжитесь с нами для получения подробной информации о наших экотуристических программах',
    
    // Contact page
    'contact.title': 'Свяжитесь с нами',
    'contact.contactInfo': 'Контактная информация',
    'contact.phone': 'Телефон',
    'contact.email': 'Email',
    'contact.address': 'Адрес',
    'contact.workingHours': 'Рабочие часы',
    'contact.mondayFriday': 'Понедельник - Пятница: 9:00 - 18:00',
    'contact.saturday': 'Суббота: 9:00 - 15:00',
    'contact.sunday': 'Воскресенье: Выходной',
    'contact.socialMedia': 'Социальные сети',
    'contact.sendMessage': 'Отправить сообщение',
    'contact.name': 'Имя',
    'contact.nameRequired': 'Имя *',
    'contact.phoneRequired': 'Телефон *',
    'contact.subject': 'Тема',
    'contact.subjectRequired': 'Тема *',
    'contact.selectSubject': 'Выберите тему',
    'contact.booking': 'Бронирование тура',
    'contact.info': 'Запрос информации',
    'contact.complaint': 'Жалоба',
    'contact.suggestion': 'Предложение',
    'contact.other': 'Другое',
    'contact.message': 'Сообщение',
    'contact.messageRequired': 'Сообщение *',
    'contact.messagePlaceholder': 'Напишите ваше сообщение...',
    'contact.sending': 'Отправка...',
    'contact.sendButton': 'Отправить сообщение',
    'contact.messageSent': 'Сообщение отправлено!',
    'contact.messageDesc': 'Мы скоро свяжемся с вами.',
    'contact.or': 'Или',
    'contact.ourLocation': 'Наше местоположение',
    'contact.mapPlaceholder': 'Здесь будет отображена карта',
    'contact.addressFull': 'г. Ташкент, Юнусабадский район',
    'contact.contactHeadline': 'Связаться с нами',
    'contact.phoneLabel': 'Телефон',
    'contact.connectTitle': 'Мы на связи',
    'contact.connectDescription': 'Мы всегда открыты к сотрудничеству и готовы помочь в планировании вашего путешествия.',
    'contact.workingHoursValue': '09:00 — 18:00',
    'contact.mapImageAlt': 'Путешествие по живописной природе Узбекистана',
    'contact.heroHighlightLine1': 'Путешествие',
    'contact.heroHighlightLine2': 'по Дальверзину',
    
    // Home page
    'home.about.label': 'О нас',
    'home.about.title': 'О нас',
    'home.about.highlight': 'путешествие вашей мечты',
    'home.about.text1': 'Мы помогаем вам найти ',
    'home.about.text2': ' и открыть красоту природы в её лучших проявлениях.',
    'home.about.description': 'Здесь вас ждут маршруты, пейзажи и впечатления, которые останутся в памяти навсегда. Мы сопровождаем на каждом этапе, чтобы ваше путешествие прошло легко и вдохновляюще.',
    'home.about.bottomText': 'Здесь вас ждут маршруты, пейзажи и впечатления, которые останутся в памяти навсегда',
    'home.about.imageAlt': 'Природа',
    'home.popular.label': 'Популярные туры',
    'home.popular.heading': 'Популярные туры',
    'home.popular.subtitle': '14 доступных направлений',
    'home.popular.loading': 'Загружаем подборку туров...',
    'home.popular.defaultBadge': 'Экотуризм',
    'home.popular.emptyState': 'Туры временно недоступны. Попробуйте обновить страницу позже.',
    'home.popular.viewAll': 'Посмотреть все туры',
    'home.popular.daysAndPeople': '{duration} дней, до {people} человек',
    'home.popular.planIncludes': 'План включает в себя',
    'home.popular.from': 'От',
    'home.whyUs.label': 'Почему мы',
    'home.whyUs.heading': 'От идеи до воплощения мечты',
    'home.whyUs.subtitle': 'Каждый маршрут продуман командой DJIDALI',
    'home.whyUs.cardTitle': 'Почему мы',
    'home.whyUs.cardDescription': 'Мы объединяем природную силу, опыт команды и индивидуальные маршруты, чтобы каждое путешествие с нами было особенным.',
    'home.experience.team': 'Команда специалистов',
    'home.experience.nature': 'Знакомство с первозданной природой',
    'home.experience.comfort': 'Комфортное проживание',
    'home.experience.routes': 'Уникальные маршруты',

    // Why Us page
    'whyUs.hero.tagline': 'DJIDALI • ПОЧЕМУ МЫ',
    'whyUs.hero.title': 'Мы — там, где природа говорит первой',
    'whyUs.hero.description': 'DJIDALI объединяет природу, комфорт и опыт, создавая путешествия, которые запоминаются.',
    'whyUs.hero.primaryCta': 'Откройте уникальные маршруты',
    'whyUs.hero.statTravelers': 'тыс счастливых путешественников',
    'whyUs.hero.statPackages': 'туристических пакета',
    'whyUs.hero.statYears': 'лет опыта',
    'whyUs.section1.title': 'Откройте для себя уникальные маршруты',
    'whyUs.section1.paragraph1': 'Наши маршруты созданы для тех, кто ищет соединение с природой без лишней суеты. Каждый тур — это продуманное путешествие, где комфорт и экологичный подход сочетаются с возможностью увидеть дикую природу в её первозданной красоте.',
    'whyUs.section1.paragraph2': 'Вы сможете пройти по тропам, по которым ходят местные егеря, и увидеть мир глазами тех, кто его действительно чувствует.',
    'whyUs.section2.paragraph': 'Мы обеспечиваем безопасность, сопровождение и максимальный комфорт на каждом этапе. Вы можете выбрать лёгкие маршруты для спокойного отдыха или насыщенные программы с элементами приключений.',
    'whyUs.section3.paragraph': 'DJIDALI — это встречи с живой природой. Каждое путешествие — возможность почувствовать ритм Узбекистана, вдохнуть свежий воздух и оставить в сердце ощущение свободы.',
    'whyUs.gallery.altForestPath': 'Лесная тропа',
    'whyUs.gallery.altMountain': 'Горный пейзаж',
    'whyUs.gallery.altCanyon': 'Тропа в ущелье',
    'whyUs.gallery.altRiverValley': 'Речная долина',
    'whyUs.gallery.altRockyRoute': 'Скалистый маршрут',
    'whyUs.gallery.altField': 'Поле',
    'whyUs.gallery.altThicket': 'Заросли',
    'whyUs.gallery.altLandscape': 'Пейзаж',
    'whyUs.gallery.altForestMassif': 'Лесной массив',

    // Wishlist page
    'wishlist.title': 'Избранное',
    'wishlist.saved': 'туров сохранено',
    'wishlist.clearAll': 'Очистить все',
    'wishlist.share': 'Поделиться',
    'wishlist.filters': 'Фильтры',
    'wishlist.sortBy': 'Сортировать по:',
    'wishlist.addedTime': 'Время добавления',
    'wishlist.byPrice': 'По цене',
    'wishlist.byRating': 'По рейтингу',
    'wishlist.byDuration': 'По длительности',
    'wishlist.showing': 'Показано',
    'wishlist.of': 'из',
    'wishlist.empty': 'Список избранного пуст',
    'wishlist.emptyDesc': 'Добавьте понравившиеся туры в избранное и просматривайте их позже',
    'wishlist.viewTours': 'Посмотреть туры',
    'wishlist.tip': '💡 Совет: Нажмите на значок сердца на карточках туров',
    'wishlist.youMightLike': 'Вам может понравиться',
    'wishlist.recommendedDesc': 'Туры, рекомендованные на основе вашего избранного',
    
    // Login page
    'login.title': 'Вход',
    'login.registerTitle': 'Регистрация',
    'login.loginDesc': 'Войдите в свой аккаунт для доступа к сафари турам',
    'login.registerDesc': 'Создайте новый аккаунт и откройте для себя сафари туры',
    'login.backToHome': 'На главную',
    'login.sideHeading': 'Путешествуйте персонально',
    'login.sideSubtitle': 'Планируйте насыщенные эко-туры с локальными экспертами и комфортом.',
    'login.sideStat1': 'Авторские маршруты по всему Узбекистану',
    'login.sideStat2': 'Профессиональные гиды и личная поддержка',
    'login.sideStat3': 'Безопасное бронирование и гибкая оплата',
    'login.fullName': 'Полное имя',
    'login.phone': 'Номер телефона',
    'login.email': 'Email',
    'login.password': 'Пароль',
    'login.confirmPassword': 'Подтвердите пароль',
    'login.firstNameLabel': 'Имя',
    'login.lastNameLabel': 'Фамилия',
    'login.firstNamePlaceholder': 'Ваше имя',
    'login.lastNamePlaceholder': 'Ваша фамилия',
    'login.rememberMe': 'Запомнить меня',
    'login.forgotPassword': 'Забыли пароль?',
    'login.loginButton': 'Войти',
    'login.registerButton': 'Зарегистрироваться',
    'login.noAccount': 'Нет аккаунта? Зарегистрируйтесь',
    'login.haveAccount': 'Есть аккаунт? Войти',
    'login.telegram': 'Telegram',
    'login.sms': 'SMS',
    'login.passwordMismatchError': 'Пароли не совпадают',
    'login.passwordMinLengthError': 'Пароль должен содержать минимум 8 символов',
    'login.genericError': 'Что-то пошло не так. Попробуйте ещё раз.',
    'login.loading': 'Загрузка...',
    'login.phoneLabel': 'Номер телефона',
    'login.phonePlaceholder': '+998 90 123 45 67',
    'login.phoneHint': 'Укажите рабочий номер телефона для связи с нашим менеджером',
    'login.phoneRequiredError': 'Номер телефона обязателен',
    'login.phoneInvalidError': 'Введите действительный номер телефона',
    'login.accessLabel': 'Вход в аккаунт',
    'login.createLabel': 'Создание аккаунта',
    'login.joinCommunityBanner': 'Присоединяйтесь к сообществу DJIDALI',
    
    // Footer
    'footer.companyName': 'DJIDALI ECO TOURISM',
    'footer.companyDesc': 'Компания экологического туризма',
    'footer.description': 'Откройте для себя самые красивые природные места Узбекистана. Мы предлагаем вам незабываемые впечатления с профессиональными гидами и безопасными сафари турами.',
    'footer.quickLinks': 'Быстрые ссылки',
    'footer.home': 'Главная',
    'footer.aboutUs': 'О нас',
    'footer.contact': 'Контакты',
    'footer.ecoTours': 'Экологические туры',
    'footer.uzbekistanTours': 'Туры по Узбекистану',
    'footer.section.about': 'О нас',
    'footer.section.tourTypes': 'Виды туризма',
    'footer.section.whyUs': 'Почему мы',
    'footer.section.social': 'Социальные сети',
    'footer.link.gallery': 'Галерея',
    'footer.link.team': 'Команда',
    'footer.tourType.eco': 'Экотуризм',
    'footer.tourType.agro': 'Агротуризм',
    'footer.tourType.teamBuilding': 'Тимбилдинг',
    'footer.tourType.sportShooting': 'Спортивная стрельба',
    'footer.tourType.hunting': 'Охотничий туризм',
    'footer.tourType.uzbekistan': 'Туры по Узбекистану',
    'footer.contactInfo': 'Контактная информация',
    'footer.addressFull': 'г. Ташкент, Юнусабадский район,\nул. Амира Темура, 108',
    'footer.workingHours': 'Пн-Пт: 9:00-18:00\nСб: 9:00-15:00',
    'footer.copyright': '© 2025 DJIDALI ECOLOGICAL TOURISM. Все права защищены.',
    'footer.privacyPolicy': 'Политика конфиденциальности',
    'footer.termsOfService': 'Условия использования',
    'footer.help': 'Помощь',
    'footer.siteSections': 'Разделы сайта',
    'footer.contactPrompt': 'Связаться с нами',
    'footer.connectWithUs': 'Оставайтесь на связи',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.noResults': 'Туры не найдены',
    'common.tryDifferentFilters': 'Попробуйте изменить фильтры поиска',
    'common.close': 'Закрыть',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.continue': 'Продолжить',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.previous': 'Предыдущий',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортировка',
    'common.view': 'Просмотр',
    'common.book': 'Забронировать',
    'common.share': 'Поделиться',
    'common.like': 'Нравится',
    'common.remove': 'Удалить',
    'common.refresh': 'Обновить список',
    'common.add': 'Добавить',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.ok': 'ОК',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.warning': 'Предупреждение',
    'common.info': 'Информация',
    'common.logout': 'Выйти',
    'common.currencyUzbekSum': 'сум'
  },
  uz: {
    // Header
    'nav.categories': 'Kategoriyalar',
    'nav.about': 'Biz haqimizda',
    'nav.contact': 'Aloqa',
    'nav.whyUs': 'Nega biz',
    'nav.wishlist': 'Sevimlilar',
    'nav.login': 'Kirish',
    'nav.adminPanel': 'Admin panel',
    'nav.userPanel': 'Kabinet',
    'nav.allCategories': 'Barcha kategoriyalar',
    
    // Hero
    'hero.title': 'O\'zbekistonning ekologik turizmini',
    'hero.subtitle': 'kashf eting',
    'hero.mobileTitle': 'Ekologik turizm',
    'hero.description': 'Tabiat bilan uyg\'unlikda unutilmas sarguzashtlar va professional gidlar bilan',
    'hero.searchPlaceholder': 'Qayerga bormoqchisiz?',
    'hero.datePlaceholder': 'Sanani tanlang',
    'hero.rangeSep12To20': '12–20 sentabr',
    'hero.rangeSep21To30': '21–30 sentabr',
    'hero.rangeOct01To10': '1–10 oktyabr',
    'hero.multiDay': 'Ko\'p kunlik',
    'hero.singleDay': 'Bir kunlik',
    'hero.unusual': 'G\'ayrioddiy',
    'hero.findTours': 'Turlarni topish',
    'hero.countryLabel': 'Shahar',
    'hero.dateLabel': 'Sana oralig\'i',
    'hero.participantsLabel': 'Ishtirokchilar',
    'hero.tourTypeLabel': 'Tur turi',
    'hero.participantsFamily': 'Oila',
    'hero.participantsSolo': 'Yakka sayohatchi',
    'hero.participantsCouple': 'Juftlik',
    'hero.participantsGroup': 'Guruh',
    'hero.hunting': 'Ovchilik',
    'hero.agro': 'Agroturizm',
    'hero.teamBuilding': 'Jamoa qurish',
    
    // Features
    'feature.mobileApp': 'Mobil ilova',
    'feature.download': 'Yuklab oling',
    'feature.discounts': 'Chegirmalar',
    'feature.upTo50': '50% gacha',
    'feature.newYear': 'Yangi yil',
    'feature.tours2026': '2026 turlari',
    'feature.monthlyTours': 'Oylik turlar',
    'feature.special': 'Maxsus',
    'feature.november': 'Noyabr',
    'feature.autumn': 'Kuz fasli',
    
    // Filters
    'filters.found': 'ta tur topildi',
    'filters.sort': 'Saralash',
    'filters.popularity': 'Mashhurligi bo\'yicha',
    'filters.price': 'Narx bo\'yicha',
    'filters.rating': 'Reyting bo\'yicha',
    'filters.filter': 'Filtr',
    'filters.duration': 'Davomiylik bo\'yicha',
    'filters.category': 'Kategoriya',
    'filters.allCategories': 'Barcha kategoriyalar',
    'filters.allSubcategories': 'Barcha subkategoriyalar',
    'filters.durationFilter': 'Davomiylik',
    'filters.priceFilter': 'Narx',
    'filters.ratingFilter': 'Reyting',
    'filters.allRatings': 'Barcha reytinglar',
    'filters.stars': 'yulduz',
    'filters.specialOffers': 'Maxsus takliflar',
    'filters.discountOnly': 'Faqat chegirmalilar',
    'filters.guaranteedOnly': 'Kafolatlangan turlar',
    'filters.language': 'Til',
    'filters.uzbek': 'O\'zbek tili',
    'filters.russian': 'Rus tili',
    'filters.english': 'Ingliz tili',
    'filters.turkish': 'Turk tili',
    'filters.clearFilters': 'Filtrlarni tozalash',
    'filters.days': 'kun',
    'filters.som': 'so\'m',
    'filters.maxPrice': 'Maksimal narx',
    'tourList.availableDirections': '14 ta mavjud yo\'nalish',
    
    // Tour cards
    'tour.author': 'Muallif',
    'tour.sponsored': 'Homiylik',
    'tour.recommended': 'Tavsiya',
    'tour.excursion': 'Ekskursiya',
    'tour.reviews': 'sharh',
    'tour.days': 'kun',
    'tour.people': 'kishi',
    'tour.upTo': 'gacha',
    'tour.from': 'dan',
    'tour.som': 'so\'m',
    'tour.defaultLocation': 'O\'zbekiston',
    'tour.priceFrom': 'Tur narxi',
    'tour.durationLabel': 'Tur davomiyligi',
    'tour.minAge': 'Minimal yosh',
    'tour.defaultMinAge': '12 yoshdan',
    'tour.type': 'Tur turi',
    'tour.defaultType': 'Ekoturizm',
    'tour.difficulty': 'Murakkablik',
    'tour.defaultDifficulty': 'Oson',
    'tour.years': 'yil',
    'tour.about': 'Tur haqida',
    'tour.included': 'Nimalar kiradi',
    'tour.excluded': 'Nimalar kirmaydi',
    'tour.moments': 'Turdan lahzalar',
    'tour.program': 'Tur dasturi',
    'tour.day': 'Kun',
    'tour.defaultDetailLocation': 'Oʻzbekiston, Chatqol tizmasi',
    'tour.descriptionFallback': 'Ushbu tur sizni tabiat qoʻyniga yetaklab, yoʻriqchi bilan sayrlar, qulay eco-mehmonxonalar va toʻliq ovqatlanish bilan taʼminlaydi.',
    'tour.defaultIncluded1': 'Eco-mehmonxonalarda yashash',
    'tour.defaultIncluded2': 'Toʻliq ovqatlanish',
    'tour.defaultIncluded3': 'Professional gid xizmatlari',
    'tour.defaultIncluded4': 'Transfer va transport',
    'tour.defaultIncluded5': 'Dasturdagi ekskursiyalar',
    'tour.defaultExcluded1': 'Shaxsiy xarajatlar',
    'tour.defaultExcluded2': 'Alkogolli ichimliklar',
    'tour.defaultExcluded3': 'Tibbiy sugʻurta',
    'tour.defaultExcluded4': 'Sovgʻalar va qoʻshimcha jihozlar',
    'tour.defaultExcluded5': 'Qoʻshimcha ekskursiyalar (soʻrovga binoan)',
    'tour.bookingTitle': 'Bron qilish va toʻlov',
    'tour.bookingDescription': 'Arizani yuboring va tasdiqlangandan soʻng Click orqali toʻlovni yakunlang.',
    'tour.bookNow': 'Turga bron qilish',
    'tour.loginToBook': 'Bron qilish uchun tizimga kiring',
    
    // Pages
    'page.backButton': 'Orqaga',
    'page.aboutUs': 'Biz haqimizda',
    'page.contact': 'Aloqa',
    'page.wishlist': 'Sevimlilar',
    'page.login': 'Kirish',
    'page.register': 'Ro\'yxatdan o\'tish',
    
    // About page
    'about.title': 'Biz haqimizda',
    'about.companyName': 'DJIDALI ECOLOGICAL TOURISM',
    'about.description': 'Toza tabiatga noyob sayohat, go\'zal tabiy manzaralarda turli xil ekoturizm tajribalarini taklif etadi.',
    'about.professionalService': 'Ekoturizm',
    'about.professionalDesc': 'O\'rmon yo\'llari va yovvoyi tabiatni kuzatish toza tabiiy muhitda',
    'about.experiencedTeam': 'Agroturizm',
    'about.experiencedDesc': 'Fermer xo\'jaligi tajribasi va mavsumiy ishlarda ishtirok',
    'about.wideGeography': 'Jamoa qurish',
    'about.wideDesc': 'Guruhlar uchun professional tashkil etilgan dasturlar',
    'about.safetyGuarantee': 'Xavfsiz sarguzashtlar',
    'about.safetyDesc': 'Professional yo\'lboshchilar bilan xavfsiz va qiziqarli marshrutlar',
    'about.ourStory': 'Bizning falsafamiz',
    'about.storyText1': 'Biz tabiatning bu burchagidagi boyliklarni mehr bilan saqlaymiz va mehmonlar bilan baham ko\'ramiz. Bizning hududimiz keng o\'rmonlar, daryolar va ko\'llarni qamrab oladi, har qadamda hayratlanarli manzaralarni taqdim etadi.',
    'about.storyText2': 'Biz turli xil faoliyatlarni taklif etamiz: o\'rmon yo\'llari va yovvoyi tabiatni kuzatish bilan ekoturizm, fermer dasturlari bilan agroturizm, jamoa qurish va barqaror tabiat bilan muloqot. Har bir tajriba sizga shahar hayotidan uzilish va tabiat bilan aloqani tiklashda yordam berish uchun ishlab chiqilgan.',
    'about.storyText3': 'Faqat manzil emas, balki mehmonlar tabiiy muhitga sho\'ng\'ishi, mahalliy qishloq xo\'jaligi amaliyotlari bilan muloqot qilishlari va samimiy mehmondo\'stlik va professional yo\'lboshchilik orqali shaxsiy yangilanish topishi mumkin bo\'lgan maxsus atmosferani taklif etamiz.',
    'about.ourMission': 'Bizning missiyamiz',
    'about.missionText': 'O\'zbekistonning bu noyob burchagidagi tabiat boyliklarini saqlash va mas\'ul va barqaror turizm amaliyotlari orqali mehmonlarimiz bilan unutilmas tajribalarni ulashish.',
    'about.ourVision': 'Bizning vazifamiz',
    'about.visionText': 'Mehmonlar haqiqiy tabiatni boshdan kechira oladigan, shahar stressidan uzila oladigan va toza tabiiy muhitda unutilmas xotiralar yarata oladigan etakchi ekoturizm yo\'nalishiga aylanish.',
    'about.contactUs': 'Biz bilan bog\'laning',
    'about.contactDesc': 'Ekoturizm dasturlarimiz haqida batafsil ma\'lumot olish uchun biz bilan bog\'laning',
    
    // Contact page
    'contact.title': 'Biz bilan bog\'laning',
    'contact.contactInfo': 'Aloqa ma\'lumotlari',
    'contact.phone': 'Telefon',
    'contact.email': 'Email',
    'contact.address': 'Manzil',
    'contact.workingHours': 'Ish vaqti',
    'contact.mondayFriday': 'Dushanba - Juma: 9:00 - 18:00',
    'contact.saturday': 'Shanba: 9:00 - 15:00',
    'contact.sunday': 'Yakshanba: Dam olish kuni',
    'contact.socialMedia': 'Ijtimoiy tarmoqlar',
    'contact.sendMessage': 'Xabar yuborish',
    'contact.name': 'Ism',
    'contact.nameRequired': 'Ism *',
    'contact.phoneRequired': 'Telefon *',
    'contact.subject': 'Mavzu',
    'contact.subjectRequired': 'Mavzu *',
    'contact.selectSubject': 'Mavzuni tanlang',
    'contact.booking': 'Tur bronlash',
    'contact.info': 'Ma\'lumot so\'rash',
    'contact.complaint': 'Shikoyat',
    'contact.suggestion': 'Taklif',
    'contact.other': 'Boshqa',
    'contact.message': 'Xabar',
    'contact.messageRequired': 'Xabar *',
    'contact.messagePlaceholder': 'Xabaringizni yozing...',
    'contact.sending': 'Yuborilmoqda...',
    'contact.sendButton': 'Xabar yuborish',
    'contact.messageSent': 'Xabar yuborildi!',
    'contact.messageDesc': 'Tez orada siz bilan bog\'lanamiz.',
    'contact.or': 'Yoki',
    'contact.ourLocation': 'Bizning joylashuvimiz',
    'contact.mapPlaceholder': 'Xarita bu yerda ko\'rsatiladi',
    'contact.addressFull': 'Toshkent shahri, Yunusobod tumani',
    'contact.contactHeadline': 'Biz bilan bogʻlaning',
    'contact.phoneLabel': 'Telefon raqami',
    'contact.connectTitle': 'Doim aloqadamiz',
    'contact.connectDescription': 'Hamkorlikka doimo tayyormiz va sayohatingizni rejalashtirishda yordam beramiz.',
    'contact.workingHoursValue': '09:00 — 18:00',
    'contact.mapImageAlt': 'Oʻzbekistonning sofligini his eting',
    'contact.heroHighlightLine1': 'Tabiat bagʻrida',
    'contact.heroHighlightLine2': 'Dalverzin sayohati',
    
    // Home page
    'home.about.label': 'Biz haqimizda',
    'home.about.title': 'Biz haqimizda',
    'home.about.highlight': 'orzularingizdagi sayohat',
    'home.about.text1': 'Biz sizga ',
    'home.about.text2': ' topishda yordam beramiz va tabiatning goʻzalligini eng yaxshi koʻrinishlarida kashf etamiz.',
    'home.about.description': 'Bu yerda esda qolarli marshrutlar, manzaralar va taassurotlar kutmoqda. Sayohatingiz engil va ilhomlantiruvchi oʻtishi uchun har bir bosqichda hamroh bo\'lamiz.',
    'home.about.bottomText': 'Bu yerda siz uchun abadiy xotirada qoladigan marshrutlar, manzaralar va taassurotlar kutmoqda',
    'home.about.imageAlt': 'Tabiat',
    'home.popular.label': 'Mashhur turlar',
    'home.popular.heading': 'Mashhur turlar',
    'home.popular.subtitle': '14 ta yoʻnalish mavjud',
    'home.popular.loading': 'Shahodatli turlar yuklanmoqda...',
    'home.popular.defaultBadge': 'Ekoturizm',
    'home.popular.emptyState': 'Turlar vaqtincha mavjud emas. Iltimos, birozdan so\'ng qayta urinib ko\'ring.',
    'home.popular.viewAll': 'Barcha turlarni koʻrish',
    'home.popular.daysAndPeople': '{duration} kun, {people} kishigacha',
    'home.popular.planIncludes': 'Rejaga kiradi',
    'home.popular.from': 'Dan',
    'home.whyUs.label': 'Nega biz',
    'home.whyUs.heading': 'Gʻoyadan orzuga aylanish',
    'home.whyUs.subtitle': 'Har bir marshrut DJIDALI jamoasi tomonidan yaratiladi',
    'home.whyUs.cardTitle': 'Nega aynan biz',
    'home.whyUs.cardDescription': 'Tabiat qudrati, jamoa tajribasi va individual marshrutlarni uyg‘unlashtirib, har bir sayohatni unutilmas qilamiz.',
    'home.experience.team': 'Mutaxassislar jamoasi',
    'home.experience.nature': 'Tabiatning asl qiyofasi',
    'home.experience.comfort': 'Qulay yashash sharoiti',
    'home.experience.routes': 'Noyob marshrutlar',

    // Why Us page
    'whyUs.hero.tagline': 'DJIDALI • NEGA BIZ',
    'whyUs.hero.title': 'Biz tabiat ovozi avval eshitiladigan joydamiz',
    'whyUs.hero.description': 'DJIDALI tabiat, qulaylik va tajribani uyg‘unlashtirib, unutilmas sayohatlar yaratadi.',
    'whyUs.hero.primaryCta': 'Noyob marshrutlarni kashf eting',
    'whyUs.hero.statTravelers': 'ming baxtli sayohatchilar',
    'whyUs.hero.statPackages': 'tayyor tur paketlari',
    'whyUs.hero.statYears': 'yillik tajriba',
    'whyUs.section1.title': 'Noyob marshrutlarni kashf eting',
    'whyUs.section1.paragraph1': 'Marshrutlarimiz tabiat bilan uyg‘unlikni izlaydiganlar uchun yaratilgan. Har bir sayohat qulaylik va ekologik yondashuv bilan uyg‘unlashgan holda noyob manzaralarni taqdim etadi.',
    'whyUs.section1.paragraph2': 'Mahalliy yo‘lboshchilar yuradigan so‘qmoqlardan o‘tib, dunyoni ularni chin dildan his qiladiganlar ko‘zi bilan ko‘ring.',
    'whyUs.section2.paragraph': 'Har bir bosqichda xavfsizlik, hamroh va maksimal qulaylikni taʼminlaymiz. Siz sokin hordiq yoki sarguzashtlarga boy dasturlarni tanlashingiz mumkin.',
    'whyUs.section3.paragraph': 'DJIDALI — bu jonli tabiat bilan uchrashuv. Har bir sayohat — Oʻzbekiston ritmini his etish, toza havodan bahramand bo‘lish va qalbingizni erkinlik bilan to‘ldirish imkoniyati.',
    'whyUs.gallery.altForestPath': 'O‘rmon so‘qmog‘i',
    'whyUs.gallery.altMountain': 'Tog‘ manzarasi',
    'whyUs.gallery.altCanyon': 'Kanyon yo‘li',
    'whyUs.gallery.altRiverValley': 'Daryo vodiysi',
    'whyUs.gallery.altRockyRoute': 'Qoyalik marshrut',
    'whyUs.gallery.altField': 'Dal',
    'whyUs.gallery.altThicket': 'Butazor',
    'whyUs.gallery.altLandscape': 'Manzara',
    'whyUs.gallery.altForestMassif': 'O‘rmon massivi',

    // Wishlist page
    'wishlist.title': 'Sevimlilar',
    'wishlist.saved': 'ta tur saqlangan',
    'wishlist.clearAll': 'Barchasini o\'chirish',
    'wishlist.share': 'Ulashish',
    'wishlist.filters': 'Filtrlar',
    'wishlist.sortBy': 'Saralash:',
    'wishlist.addedTime': 'Qo\'shilgan vaqt bo\'yicha',
    'wishlist.byPrice': 'Narx bo\'yicha',
    'wishlist.byRating': 'Reyting bo\'yicha',
    'wishlist.byDuration': 'Davomiylik bo\'yicha',
    'wishlist.showing': 'Ko\'rsatilmoqda',
    'wishlist.of': 'dan',
    'wishlist.empty': 'Sevimlilar ro\'yxati bo\'sh',
    'wishlist.emptyDesc': 'Yoqgan turlaringizni sevimlilar ro\'yxatiga qo\'shing va keyinroq ko\'ring',
    'wishlist.viewTours': 'Turlarni ko\'rish',
    'wishlist.tip': '💡 Maslahat: Tur kartasidagi yurak belgisini bosing',
    'wishlist.youMightLike': 'Sizga yoqishi mumkin',
    'wishlist.recommendedDesc': 'Sevimlilaringiz asosida tavsiya etilgan turlar',
    
    // Login page
    'login.title': 'Hisobga kirish',
    'login.registerTitle': 'Ro\'yxatdan o\'tish',
    'login.loginDesc': 'Safari turlariga kirish uchun hisobingizga kiring',
    'login.registerDesc': 'Yangi hisob yaratib safari turlarini kashf eting',
    'login.backToHome': 'Bosh sahifaga qaytish',
    'login.sideHeading': 'Shaxsiylashtirilgan sayohatlar',
    'login.sideSubtitle': 'Mahalliy ekspertlar bilan uygʻun ekoturlarni rejalashtiring.',
    'login.sideStat1': 'Oʻzbekiston boʻylab tanlangan marshrutlar',
    'login.sideStat2': 'Tajriba orttirgan gidlar va shaxsiy yordam',
    'login.sideStat3': 'Xavfsiz bron va moslashuvchan toʻlovlar',
    'login.fullName': 'To\'liq ism',
    'login.phone': 'Telefon raqam',
    'login.email': 'Email',
    'login.password': 'Parol',
    'login.confirmPassword': 'Parolni tasdiqlang',
    'login.firstNameLabel': 'Ism',
    'login.lastNameLabel': 'Familiya',
    'login.firstNamePlaceholder': 'Ismingiz',
    'login.lastNamePlaceholder': 'Familiyangiz',
    'login.rememberMe': 'Meni eslab qol',
    'login.forgotPassword': 'Parolni unutdingizmi?',
    'login.loginButton': 'Kirish',
    'login.registerButton': 'Ro\'yxatdan o\'tish',
    'login.noAccount': 'Hisobingiz yo\'qmi? Ro\'yxatdan o\'ting',
    'login.haveAccount': 'Hisobingiz bormi? Kirish',
    'login.telegram': 'Telegram',
    'login.sms': 'SMS',
    'login.passwordMismatchError': 'Parollar mos emas',
    'login.passwordMinLengthError': 'Parol kamida 8 ta belgidan iborat bo\'lishi kerak',
    'login.genericError': 'Xatolik yuz berdi. Iltimos, qayta urinib ko\'ring.',
    'login.loading': 'Yuklanmoqda...',
    'login.phoneLabel': 'Telefon raqam',
    'login.phonePlaceholder': '+998 90 123 45 67',
    'login.phoneHint': 'Operatorimiz siz bilan bog\'lanishi uchun haqiqiy raqamni kiriting',
    'login.phoneRequiredError': 'Telefon raqami majburiy',
    'login.phoneInvalidError': 'To\'g\'ri telefon raqamini kiriting',
    'login.accessLabel': 'Hisobga kirish',
    'login.createLabel': 'Hisob yaratish',
    'login.joinCommunityBanner': 'DJIDALI hamjamiyatiga qo\'shiling',
    
    // Footer
    'footer.companyName': 'DJIDALI ECO TOURISM',
    'footer.companyDesc': 'Ekologik turizm kompaniyasi',
    'footer.description': 'O\'zbekistonning eng go\'zal tabiat joylarini kashf eting. Biz professional gidlar va xavfsiz safari turlari bilan sizga unutilmas tajriba taqdim etamiz.',
    'footer.quickLinks': 'Tezkor havolalar',
    'footer.home': 'Bosh sahifa',
    'footer.aboutUs': 'Biz haqimizda',
    'footer.contact': 'Aloqa',
    'footer.ecoTours': 'Ekologik turlar',
    'footer.uzbekistanTours': 'O\'zbekiston turlari',
    'footer.section.about': 'Biz haqimizda',
    'footer.section.tourTypes': 'Tur turlari',
    'footer.section.whyUs': 'Nega biz',
    'footer.section.social': 'Ijtimoiy tarmoqlar',
    'footer.link.gallery': 'Galereya',
    'footer.link.team': 'Jamoa',
    'footer.tourType.eco': 'Ekoturizm',
    'footer.tourType.agro': 'Agroturizm',
    'footer.tourType.teamBuilding': 'Jamoa qurish',
    'footer.tourType.sportShooting': 'Sport o\'q otish',
    'footer.tourType.hunting': 'Ov turizmi',
    'footer.tourType.uzbekistan': 'O\'zbekiston turlari',
    'footer.contactInfo': 'Aloqa ma\'lumotlari',
    'footer.addressFull': 'Toshkent shahri, Yunusobod tumani,\nAmir Temur ko\'chasi, 108-uy',
    'footer.workingHours': 'Dush-Juma: 9:00-18:00\nShanba: 9:00-15:00',
    'footer.copyright': '© 2025 DJIDALI ECOLOGICAL TOURISM. Barcha huquqlar himoyalangan.',
    'footer.privacyPolicy': 'Maxfiylik siyosati',
    'footer.termsOfService': 'Foydalanish shartlari',
    'footer.help': 'Yordam',
    'footer.siteSections': 'Sayt bo‘limlari',
    'footer.contactPrompt': 'Biz bilan bog‘laning',
    'footer.connectWithUs': 'Biz bilan aloqada bo‘ling',
    
    // Common
    'common.loading': 'Yuklanmoqda...',
    'common.noResults': 'Turlar topilmadi',
    'common.tryDifferentFilters': 'Qidiruv filtrlarini o\'zgartirib ko\'ring',
    'common.close': 'Yopish',
    'common.save': 'Saqlash',
    'common.cancel': 'Bekor qilish',
    'common.continue': 'Davom etish',
    'common.back': 'Orqaga',
    'common.next': 'Keyingi',
    'common.previous': 'Oldingi',
    'common.search': 'Qidirish',
    'common.filter': 'Filtr',
    'common.sort': 'Saralash',
    'common.view': 'Ko\'rish',
    'common.book': 'Bron qilish',
    'common.share': 'Ulashish',
    'common.like': 'Yoqtirish',
    'common.remove': 'O\'chirish',
    'common.refresh': 'Ro\'yxatni yangilash',
    'common.add': 'Qo\'shish',
    'common.edit': 'Tahrirlash',
    'common.delete': 'O\'chirish',
    'common.confirm': 'Tasdiqlash',
    'common.yes': 'Ha',
    'common.no': 'Yo\'q',
    'common.ok': 'OK',
    'common.error': 'Xato',
    'common.success': 'Muvaffaqiyat',
    'common.warning': 'Ogohlantirish',
    'common.info': 'Ma\'lumot',
    'common.logout': 'Chiqish',
    'common.currencyUzbekSum': 'so\'m'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }

    if (translations.ru && translations.ru[key]) {
      return translations.ru[key];
    }

    if (translations.en && translations.en[key]) {
      return translations.en[key];
    }

    if (process.env.NODE_ENV !== 'production') {
      console.warn(`[i18n] Missing translation for key: ${key}`);
    }

    return key;
  };

  const translate = (input: TranslateArgs | string): string => {
    if (typeof input === 'string') {
      return t(input);
    }

    const { ru, uz, en } = input;
    if (language === 'ru') {
      return ru;
    }
    if (language === 'uz') {
      return uz;
    }
    return en ?? ru;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};